- id: airing
  alias: airing
  description: 'Turns off heating'
  trigger:
  - platform: state
    entity_id: input_boolean.heating
    to: 'off'
    from: 'on'
  condition: []
  action:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.pompa
  - service: notify.mobile_app_ipad
    data:
      message: Heating OFF
  mode: single
  max: 10
- alias: heating_all
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.heating_all
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: notify.mobile_app_ipad
    data:
      message: Heating ON
  mode: single
- alias: heating_rooms
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.heating_rooms
    to: 'on'
    from: 'off'
  condition: []
  action:
  - service: notify.mobile_app_ipad
    data:
      message: Heating ON
  mode: single
- id: SzuszenieReczników-O
  alias: SzuszenieReczników-O
  description: ''
  trigger:
  - platform: time_pattern
    hours: '18'
  - platform: time_pattern
    hours: '05'
  condition:
  - condition: state
    entity_id: input_boolean.heating_all
    state: 'on'
  action:
  - scene: scene.suszenierecznikow
  mode: single
- id: '1622404158462'
  alias: NotifyWhenSirenChanges
  description: ''
  trigger:
  - platform: state
    entity_id:
    - switch.syrenapietro_switch
    from: 'on'
    to: 'off'
  condition: []
  action:
  - service: notify.mobile_app_oppo5
    data:
      message: Syrena zmieniła stan
  - service: notify.mobile_app_blackberry_z10
    data:
      message: Syrena wlaczona
  mode: single
- alias: notification_heating_calculation_not_possible
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.heating_calculation_all
    to: unavailable
  condition: []
  action:
  - service: notify.mobile_app_oppo5
    data:
      message: Kalkulacja grzania niemożliwa
  mode: single
- alias: nSuszenieReczników-Off
  description: ''
  trigger:
  - platform: time_pattern
    hours: '22'
    minutes: '00'
  - platform: time_pattern
    hours: 08
  condition: []
  action:
  - service: scene.turn_on
    target:
      entity_id: scene.suszenierecznikowoff
    metadata: {}
  mode: single

- id: turn_on_heating_source_all
  alias: turn_on_heating_source_all
  description: When temperature that is set
  triggers:
    - hours: "*"
      minutes: "*"
      seconds: "30"
      trigger: time_pattern
  conditions:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.heating_all
        state: "on"
      - condition: state
        entity_id: switch.pompa
        state: "off"
      - condition: numeric_state
        entity_id: sensor.heating_calculation_all
        above: input_number.temperature_diff_all
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.pompa
  - data:
      message: Pompa ON
    action: notify.mobile_app_ipad
  mode: single

- id: turn_off_heating_source_all_devices
  alias: turn_off_heating_source_all_devices
  description: When temperature that is set
  triggers:
  - hours: "*"
    minutes: "*"
    seconds: "30"
    trigger: time_pattern
  conditions:
  - condition: numeric_state
    entity_id: sensor.heating_calculation_all
    below: input_number.temperature_diff_all
  - condition: state
    entity_id: switch.pompa
    state: "on"
  - condition: state
    entity_id: input_boolean.heating_all
    state: "on"
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.pompa
  mode: single

- id: turn_on_heating_source_rooms
  alias: turn_on_heating_source_rooms
  description: When temperature that is set
  triggers:
    - hours: "*"
      minutes: "*"
      seconds: "30"
      trigger: time_pattern
  conditions:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.heating_rooms
        state: "on"
      - condition: state
        entity_id: switch.pompa
        state: "off"
      - condition: numeric_state
        entity_id: sensor.heating_calculation_rooms
        above: input_number.temperature_diff_rooms
  actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.pompa
  - data:
      message: Pomp ON
    action: notify.mobile_app_ipad
  mode: single

- alias: turn_off_heating_source_rooms
  id: turn_off_heating_source_rooms
  description: When temperature that is set
  triggers:
  - hours: "*"
    minutes: "*"
    seconds: "30"
    trigger: time_pattern
  conditions:
  - condition: numeric_state
    entity_id: sensor.heating_calculation_rooms
    below: input_number.temperature_diff_rooms
  - condition: state
    entity_id: switch.pompa
    state: "on"
  - condition: state
    entity_id: input_boolean.heating_rooms
    state: "on"
  actions:
  - action: switch.turn_off
    metadata: {}
    data: {}
    target:
      entity_id: switch.pompa
  mode: single
