# Configure a default setup of Home Assistant (frontend, api, etc)

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.11.12.10
    - 192.168.30.0/24
    - 192.168.70.0/24
    - 172.17.0.0/16
    - 172.19.0.0/16
    - 127.0.0.1

homekit:
  #advertise_ip: "172.17.0.2"
  name: "HABridge"
  port: 21063
  advertise_ip: "10.10.10.10"
  #ip_address: "10.10.10.10"
  filter:
    include_domains:
      - automation
      - input_boolean

prometheus:
#  namespace: ha

recorder:
  db_url: mysql://thish4_ha:Pejkoq-tabpar-mukbo4@aniskop.mysql.dhosting.pl:3306/ahyei7_homeassistant?charset=utf8mb4
  purge_keep_days: 365


logger:
  default: warning
#  logs:
#    custom_components.bosch: debug
#    bosch_thermostat_client: debug
#influxdb:
#  api_version: 2
#  host: !secret influxdb_host
#  port: 8086
#  database: home_assistant
#  bucket: ha
#  organization: home
#  token: !secret influxdb_token
#  ssl: false

default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
#script: !include scripts.yaml
scene: !include scenes.yaml
timer: !include timers.yaml
template: !include templates.yaml

#duckdns:
#  domain: !secret duckdns_domain
#  access_token: !secret duckdns_token

#sensor:
#  - platform: rest
#    resource: !secret solar_url
#    method: POST
#    name: Cumulative Production kWh
#    scan_interval: 300
#    headers:
#      Authorization: bearer !secret solar_authorization
#      Content-Type: application/json
#    payload: '{  "deviceSn": "!secret solar_device" }'
#    value_template: "{{ value_json.dataList[23].value }}"
